### ISSUE TITLE
Data never received

### ISSUE THREAD

**Issue by MrYsLab** [changyuheng/aioserial#2]
Hi,
   I am trying to do something fairly simple. I have a serial device (a micro:bit) that when I send it a 'g' followed by a carriage return, it returns a string of data.

Using a terminal emulator, If I do this, here is the string I get back:
16,-96,-1008,False,False,0,0,0,9,9,5

The data is generated via a Micropython print() function, so the string is terminated with '\n'

I wrote the following program with aioserial, but I am not receiving anything back:
```
import aioserial
import asyncio

async def read_and_print(aioserial_instance: aioserial.AioSerial):
    cmd = 'g\n'
    cmd = bytes(cmd.encode())
    print('send', await aioserial_instance.write_async(cmd))
    await asyncio.sleep(2)

    print(('received: ', await aioserial_instance.readline_async()).decode(errors='ignore'), end='', flush=True)

asyncio.run(read_and_print(aioserial.AioSerial(port='/dev/ttyACM0')))
```
I've tried this with and without the sleep, and the behavior is the same.

I see that I sent 2 bytes based on the first print statement, but I never received anything back.
I also tried using read_async and the same result.

I am guessing my code contains some dumb mistake. Could you please tell me what I did wrong?
Thanks.

**Comment by MrYsLab** [comment]
Thanks for the quick reply. There seems to be a syntax error in the line you provided above. It throws an AttributeError exception. I am not too worried about that now, but  provided my code and the console output for you at the bottom of this comment.

My main concern is when I run the following code, where I try to retrieve the number of bytes wating. I see that the 2 bytes are sent, but the number of bytes waiting is always zero. I am running Python 3.7.1 on Ubuntu 18.10. Any thoughts?
```
import aioserial
import asyncio


async def read_and_print(aioserial_instance: aioserial.AioSerial):
    cmd = 'g\n'
    cmd = bytes(cmd.encode())
    print('send', await aioserial_instance.write_async(cmd))

    while not aioserial_instance.in_waiting:
        await asyncio.sleep(.1)
        print(aioserial_instance.in_waiting)

asyncio.run(read_and_print(aioserial.AioSerial(port='/dev/ttyACM0')))

```
Below are the code and syntax error mentioned above:
```
import aioserial
import asyncio


async def read_and_print(aioserial_instance: aioserial.AioSerial):
    cmd = 'g\n'
    cmd = bytes(cmd.encode())
    print('send', await aioserial_instance.write_async(cmd))

    print('received: ', print('received: ', await aioserial_instance.read_async(aioserial_instance.in_waiting)).decode(errors='ignore'),
          end='', flush=True)

asyncio.run(read_and_print(aioserial.AioSerial(port='/dev/ttyACM0')))

Traceback (most recent call last):
  File "/home/afy/PycharmProjects/asyncio_ser/experimental/aioser_play2.py", line 12, in <module>
    asyncio.run(read_and_print(aioserial.AioSerial(port='/dev/ttyACM0')))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/home/afy/PycharmProjects/asyncio_ser/experimental/aioser_play2.py", line 10, in read_and_print
    print('received: ', print('received: ', await aioserial_instance.read_async(aioserial_instance.in_waiting)).decode(errors='ignore'), end='', flush=True)
AttributeError: 'NoneType' object has no attribute 'decode'
send 2
received:  b''

```

**Comment by changyuheng** [comment]
A few questions:

1. What was the output of
print('send', await aioserial_instance.write_async(cmd))

2. Was in_waiting ever not 0?
print(aioserial_instance.in_waiting)

3. What's the version of pyserial you used?

--

Syntax error part:
The below line has parenthesis in wrong place. decode was used at as a method of the return type of print but the type of it is actually None.
print('received: ', print('received: ', await aioserial_instance.read_async(aioserial_instance.in_waiting)).decode(errors='ignore'),
          end='', flush=True)

**Comment by MrYsLab** [comment]
Well I was correct - I did do something dumb - I forgot to set the baudrate to 115200. It all works now.
Sorry to have wasted your time.

BTW, I am very appreciative that the library runs in Windows as well as in Linux. I am now off to trying to integrate your library with the asyncio version of pyzeromq. 

Thanks again.

**Comment by changyuheng** [comment]
Glad to hear the problem is solved.
