### ISSUE TITLE
recv data is not correct

### ISSUE THREAD

**Issue by xzzh999** [changyuheng/aioserial#4]
Hi~

when i send follow many times (in hex, no \r\n): 
```
01 01 00 00 00 00 
```
recv are:
```
b'\x07\x07\x83\x06\x06\x86'
b'IHII\xc9\xc9'
b'%%\x01!!%'
```
and the recv code is:
```
res = await self.ins.read_async(size=AckMsg.ack_size())
print("read data ok!", res)
```
why?

**Comment by xzzh999** [comment]
and sometimes can not recv any data...

**Comment by changyuheng** [comment]
Do you have baud and other settings configured correctly?

**Comment by xzzh999** [comment]
@changyuheng 
yes, i make sure the configure is correct.
```
self.ins = aioserial.AioSerial(port=self.port, 
                      baudrate=self.baudrate, stopbits=self.stopbit, bytesize=self.databit)
```

**Comment by changyuheng** [comment]
Are you able to get correct information through other terminal applications such as minicom?

**Comment by xzzh999** [comment]
yes, i use pyserial-asyncio, it's correct...

**Comment by changyuheng** [comment]
Can you please try with pySerial as the APIs of it are more similar with aioserial?
And please also post both code snippets based on pySerial and aioserial and their results here.

**Comment by xzzh999** [comment]
I make two serial port ``COM5`` and ``COM7``, and connect them together, i send very simple data to ``COM5``, so ``COM7`` can print the data, the code is very simple, just like as the read me:
```
self.ins = aioserial.AioSerial(port=self.port, baudrate=self.baudrate, 
     stopbits=self.stopbit, bytesize=self.databit)
```
```
 while True:
    print((await self.ins.read_async()).decode(errors='ignore'), end='', flush=True)
```
just open a port, and keep reading, and use many other serial port tools to send data.

**Comment by changyuheng** [comment]
Hi, I see you may be a Chinese. Do you want to talk in Chinese instead? 中文可能比較方便溝通

**Comment by xzzh999** [comment]
可以的。
就是我有2根USB串口线互联，分别对应COM5和COM7, 用串口工具测试收发数据，aioserial的发送总是正常的，但是接收是错误的数据。

**Comment by changyuheng** [comment]
可以麻煩分別用 `pySerial` 和 `aioserial` 做一樣的測試，並把程式碼和結果都在這邊分別列出來嗎？`pySerial` 和 `aioserial` 的 API 非常像，差別只在於 `aioserial` 的 API 是 async。希望可以看到像這個[回答](https://stackoverflow.com/a/52490384/1592410)中可以執行的程式碼，以及其結果。
為希望能用 `pySerial` 來比較是因為，`aioserial` 的所有 API 都是直接以 `pySerial` 的 API 為基礎，問題很有可能是出在 `pySerial` 身上。

**Comment by xzzh999** [comment]
ok, i will do that later,  for now i must complete my project stuff first..

**Comment by changyuheng** [comment]
Any updates @xzzh999?
